ptro_rencontres_homepage:
    path:     /accueil/{tri}
    defaults:
        _controller: 	PTRORencontresBundle:Main:accueil
        tri:    nouveau
    requirements:
        tri: nouveau|pres_vous|visite

ptro_maj_affichage:
    path:     /accueil-modif-affichage
    defaults:
        _controller: 	PTRORencontresBundle:Main:affichage

ptro_rencontres_profil:
    path:     /profil/{id}
    defaults:
        _controller: 	PTRORencontresBundle:Main:profil
    requirements:
        id: \d+