ptro_rencontres_homepage:
    path:     /accueil/{tri}
    defaults:
        _controller: 	PTRORencontresBundle:Main:accueil
        tri:    nouveau
    requirements:
        tri: nouveau|pres_vous|visite

ptro_maj_affichage:
    path:     /accueil-modif-affichage
    defaults:
        _controller: 	PTRORencontresBundle:Main:affichage

ptro_rencontres_profil:
    path:     /profil/{id}
    defaults:
        _controller: 	PTRORencontresBundle:Main:profil
    requirements:
        id: \d+

ptro_rencontres_recherche:
    path:     /recherche
    defaults:
        _controller:    PTRORencontresBundle:Main:recherche

ptro_rencontres_favoris:
    path:     /favoris
    defaults:
        _controller:    PTRORencontresBundle:Main:favoris

ptro_rencontres_mon_profil:
    path:     /mon_profil
    defaults:
        _controller:    PTRORencontresBundle:Main:monProfil

ptro_rencontres_mes_messages:
    path:     /mes_messages
    defaults:
        _controller:    PTRORencontresBundle:Main:mesMessages

ptro_rencontres_discussion:
    path:     /discussion/{idProfil}
    defaults:
        _controller:    PTRORencontresBundle:Main:discussion
    requirements:
        idProfil: \d+

ptro_rencontres_messages_suppr:
    path:     /messages_suppr
    defaults:
        _controller:    PTRORencontresBundle:Main:messagesSuppr

ptro_rencontres_mes_contacts:
    path:     /mes_contacts
    defaults:
        _controller:    PTRORencontresBundle:Main:mesContacts