ptro_rencontres_homepage:
    path:     /accueil/{tri}
    defaults:
        _controller: 	PTRORencontresBundle:Main:accueil
        tri:    nouveau
    requirements:
        tri: nouveau|pres_vous|visite

ptro_maj_affichage:
    path:     /accueil-modif-affichage
    defaults:
        _controller: 	PTRORencontresBundle:Main:affichage

ptro_rencontres_profil:
    path:     /profil/{id}
    defaults:
        _controller: 	PTRORencontresBundle:Main:profil
    requirements:
        id: \d+

ptro_rencontres_recherche:
    path:     /recherche
    defaults:
        _controller:    PTRORencontresBundle:Main:recherche

ptro_rencontres_favoris:
    path:     /favoris
    defaults:
        _controller:    PTRORencontresBundle:Main:favoris

ptro_rencontres_mon_profil:
    path:     /mon_profil
    defaults:
        _controller:    PTRORencontresBundle:Main:monProfil

ptro_rencontres_mes_messages:
    path:     /mes_messages
    defaults:
        _controller:    PTRORencontresBundle:Main:mesMessages

ptro_rencontres_discussion:
    path:     /discussion/{idProfil}
    defaults:
        _controller:    PTRORencontresBundle:Main:discussion
    requirements:
        idProfil: \d+

ptro_rencontres_messages_suppr:
    path:     /messages_suppr
    defaults:
        _controller:    PTRORencontresBundle:Main:messagesSuppr

ptro_rencontres_mes_contacts:
    path:     /mes_contacts
    defaults:
        _controller:    PTRORencontresBundle:Main:mesContacts

ptro_rencontres_inscription:
    path:     /inscription
    defaults:
        _controller:    PTRORencontresBundle:Main:inscription

ptro_rencontres_mail:
    path:     /mail
    defaults:
        _controller:    PTRORencontresBundle:Main:mail

ptro_photo_submit:
    path:     /photo_submit
    defaults:
        _controller:    PTRORencontresBundle:Profile:photoSubmit
    methods:  [POST]

ptro_rencontres_suppr_photo:
    path:     /suppr_photo/{ordre}
    defaults:
        _controller: 	PTRORencontresBundle:Profile:supprPhoto
    requirements:
        id: \d+

ptro_rencontres_modif_miniature_ajax:
    path:     /modif_miniature_ajax
    defaults:
        _controller:    PTRORencontresBundle:Profile:modifMiniature

ptro_rencontres_change_photo_principale:
    path: /change_photo_principale/{ordre}
    defaults:
        _controller: 	PTRORencontresBundle:Profile:changePhotoPrincipale
    requirements:
        id: \d+

ptro_rencontres_message_ajax:
    path:     /message_ajax
    defaults:
        _controller:    PTRORencontresBundle:Main:message