services:
#    ptro_rencontres.example:
#        class: PTRO\RencontresBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    my.listenerEvenement:
        class: PTRO\RencontresBundle\EventListener\CreationEvenement
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    PTRO.form.flow.createUtilisateur:
        class: PTRO\RencontresBundle\Form\CreateUtilisateurFlow
        parent: craue.form.flow
