<?php

namespace PTRO\RencontresBundle\Repository;

/**
 * AlcoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlcoolRepository extends \Doctrine\ORM\EntityRepository
{
}
