<?php

namespace PTRO\RencontresBundle\Repository;

/**
 * BlocageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocageRepository extends \Doctrine\ORM\EntityRepository
{
}
