<?php

namespace PTRO\RencontresBundle\Repository;

/**
 * CigaretteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CigaretteRepository extends \Doctrine\ORM\EntityRepository
{
}
