<?php

namespace PTRO\RencontresBundle\Repository;

/**
 * CouleurYeuxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouleurYeuxRepository extends \Doctrine\ORM\EntityRepository
{
}
