<?php

namespace PTRO\RencontresBundle\Repository;

/**
 * CouleurCheveuxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouleurCheveuxRepository extends \Doctrine\ORM\EntityRepository
{
}
