<?php

namespace PTRO\RencontresBundle\Repository;

/**
 * EtatCivilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatCivilRepository extends \Doctrine\ORM\EntityRepository
{
}
