<?php

namespace PTRO\RencontresBundle\Repository;

/**
 * FavoriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFavoriByUsers($receveur, $createur){
        $queryBuilder = $this->createQueryBuilder('c');
        $queryBuilder->where('c.receveur=:receveur')
            ->andWhere('c.createur=:createur')
            ->setParameters(array('receveur' => $receveur, 'createur' => $createur));
        $query = $queryBuilder->getQuery();
        $result = $query->getOneOrNullResult();
        return $result;
    }
}
