<?php

namespace PTRO\RencontresBundle\Repository;

/**
 * FavoriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriRepository extends \Doctrine\ORM\EntityRepository
{
}
