<?php

namespace PTRO\RencontresBundle\Repository;

/**
 * OrientationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrientationRepository extends \Doctrine\ORM\EntityRepository
{
}
