<?php

namespace PTRO\RencontresBundle\Repository;

/**
 * PhysiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhysiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
