<?php

namespace PTRO\RencontresBundle\Repository;

/**
 * PokeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPokeTodayByUsers($receveur, $createur){
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->where('p.receveur=:receveur')
            ->andWhere('p.createur=:createur')
            ->andWhere('p.datePoke LIKE :dateToday')
            ->setParameters(array('receveur' => $receveur, 'createur' => $createur, 'dateToday' => new \DateTime('Y-m-d')."%"));
        $query = $queryBuilder->getQuery();
        $result = $query->getOneOrNullResult();
        return $result;
    }
}
