<?php

namespace PTRO\RencontresBundle\Repository;

/**
 * PokeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokeRepository extends \Doctrine\ORM\EntityRepository
{
}
