<?php

namespace PTRO\RencontresBundle\Repository;

/**
 * RelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationRepository extends \Doctrine\ORM\EntityRepository
{
}
